### ISSUE TITLE
No source package url

### ISSUE THREAD

**Issue by mhiramat** [stffrdhrn/or1k-toolchain-build#1]
Since build-gcc.sh expects there are source tarballs under cache directory, if I follow the README.md, it just failed to run.
I would like to suggest that the build-gcc.sh should check the source tarballs at first. And if there aren't, download it from recommended site. (Or, at least update README.md to point where user can get the sources.)

**Comment by stffrdhrn** [comment]
Sorry, I am just seeing this. You are right I know if the limitation, I was just lazy. I'll fix it soon.  We just got a new cleanroom rewrite gcc port.

**Comment by stffrdhrn** [comment]
This should be fixed with f8e9b8f989f5af023f7adaffb11302fc114ab58d.  Let me know if you try again, I have also moved to `musl-cross-make` and the new GCC toolchain which is still under testing.
